"use client";

import { useTranslation } from "react-i18next";
import type { StoreBranchLabels } from "./store-branch-types";

export function useStoreBranchLabels(): StoreBranchLabels {
  const { t } = useTranslation();

  return {
    active: t("common.active"),
    actions: t("common.actions"),
    addBranch: t("settings.storeBranch.addBranch"),
    addStore: t("settings.storeBranch.addStore"),
    address: t("fields.branch_address"),
    branch: t("nav.branch"),
    branchDetails: t("settings.storeBranch.branchDetails"),
    branchHint: t("settings.storeBranch.branchHint"),
    branchInfo: t("settings.storeBranch.branchInfo"),
    branchList: t("settings.storeBranch.branchList"),
    branchNameRequired: t("settings.storeBranch.branchNameRequired"),
    cancel: t("actions.cancel"),
    cancelImage: t("settings.storeBranch.cancelImage"),
    charge: t("settings.storeBranch.charge"),
    chargePercent: t("settings.storeBranch.chargePercent"),
    closed: t("settings.storeBranch.closed"),
    contactDetails: t("settings.storeBranch.contactDetails"),
    contactHint: t("settings.storeBranch.contactHint"),
    cropHint: t("settings.storeBranch.cropHint"),
    cropImage: t("settings.storeBranch.cropImage"),
    current: t("settings.storeBranch.current"),
    delete: t("actions.delete"),
    deleteConfirm: t("settings.deleteConfirm"),
    deleteFailed: t("settings.deleteFailed"),
    email: t("fields.email"),
    emailPlaceholder: t("settings.emailPlaceholder"),
    general: t("settings.storeBranch.general"),
    horizontal: t("settings.storeBranch.horizontal"),
    imageLoadFailed: t("settings.storeBranch.imageLoadFailed"),
    imageSupport: t("settings.storeBranch.imageSupport"),
    inactive: t("common.inactive"),
    name: t("fields.name"),
    nameEn: t("fields.nameEn"),
    nameLa: t("fields.nameLa"),
    noBranch: t("settings.storeBranch.noBranch"),
    noStore: t("settings.storeBranch.noStore"),
    open: t("settings.storeBranch.open"),
    phone: t("fields.phone"),
    plc: t("settings.storeBranch.plc"),
    refreshBranch: t("settings.storeBranch.refreshingBranchList"),
    refreshStore: t("settings.storeBranch.refreshingStoreList"),
    resetFailed: t("settings.storeBranch.resetFailed"),
    resetPassword: t("settings.storeBranch.resetPassword"),
    save: t("actions.save"),
    saveFailed: t("settings.saveFailed"),
    saved: t("settings.saved"),
    savingHint: t("settings.storeBranch.savingHint"),
    savingTitle: t("settings.storeBranch.savingTitle"),
    selectAll: t("common.selectAll"),
    selectRecord: t("settings.storeBranch.selectRecord"),
    store: t("nav.store"),
    storeDetails: t("settings.storeBranch.storeDetails"),
    storeEmailRequired: t("settings.storeBranch.storeEmailRequired"),
    storeHint: t("settings.storeBranch.storeHint"),
    storeInfo: t("settings.storeBranch.storeInfo"),
    storeList: t("settings.storeBranch.storeList"),
    storeNameRequired: t("settings.storeBranch.storeNameRequired"),
    storeRequired: t("settings.storeRequired"),
    taxBilling: t("settings.storeBranch.taxBilling"),
    taxBillingHint: t("settings.storeBranch.taxBillingHint"),
    type: t("settings.storeBranch.type"),
    uploadImage: t("settings.storeBranch.uploadImage"),
    vertical: t("settings.storeBranch.vertical"),
    vat: t("settings.storeBranch.vat"),
    vatPercent: t("settings.storeBranch.vatPercent"),
    zoom: t("settings.storeBranch.zoom")
  };
}
